# The distributed Windows engine must not require a separate VC++ redistributable.
# See https://doc.rust-lang.org/reference/linkage.html#static-and-dynamic-c-runtimes
[target.'cfg(all(target_os = "windows", target_env = "msvc"))']
rustflags = ["-C", "target-feature=+crt-static"]
