use super::{get_build_steps, get_cmd, get_path, paths, render_template, GeneratedFile};
use anyhow::{bail, Context, Result};
use serde_yaml::Value;
use std::{
    collections::{BTreeMap, BTreeSet},
    fs,
    io::Write,
    path::Path,
};

const ARCHIVE: &str = "source.zip";

pub(crate) fn create(
    spec: &Value,
    target: &str,
    ctx: &BTreeMap<String, String>,
    root: &Path,
    files: &[GeneratedFile],
) -> Result<()> {
    let build = get_build_steps(spec, target)?;
    let run = vec![get_cmd(spec, &["targets", target, "run", "cmd"])?];
    let dotnet = get_path(spec, &["engine_project"]).is_some();
    let mut sources = BTreeSet::new();
    for file in files {
        sources.insert(paths::relative_file(&render_template(
            &file.path,
            &Value::Null,
            ctx,
        ))?);
    }
    if dotnet {
        sources.insert("CrexeApp.csproj".into());
    }
    let mut commands = vec![("build", build), ("run", run)];
    if dotnet {
        commands.push((
            "publish",
            vec![vec![
                "dotnet".into(),
                "publish".into(),
                "CrexeApp.csproj".into(),
                "-c".into(),
                "Release".into(),
                "-o".into(),
                "publish".into(),
                "--self-contained".into(),
                "false".into(),
            ]],
        ));
        commands.push((
            "test",
            vec![vec![
                "dotnet".into(),
                "build/CrexeApp.dll".into(),
                "--crexe-self-test".into(),
            ]],
        ));
    }
    let windows = cfg!(windows);
    for (name, steps) in commands {
        let filename = format!("{name}.{}", if windows { "bat" } else { "sh" });
        let mut script = if windows {
            "@echo off\r\nsetlocal DisableDelayedExpansion\r\ncd /d \"%~dp0\"\r\n".to_owned()
        } else {
            "#!/bin/sh\nset -eu\ncd -- \"$(dirname -- \"$0\")\"\n".to_owned()
        };
        for args in steps {
            let rendered: Vec<_> = args
                .iter()
                .map(|arg| render_template(arg, spec, ctx))
                .collect();
            let quoted: Result<Vec<_>> = rendered.iter().map(|arg| quote(arg, windows)).collect();
            if windows {
                script.push_str("call ");
            }
            script.push_str(&quoted?.join(" "));
            script.push_str(if windows {
                "\r\nif errorlevel 1 exit /b %errorlevel%\r\n"
            } else {
                "\n"
            });
        }
        fs::write(root.join(&filename), script)?;
        sources.insert(filename.into());
    }
    let instructions = format!("# Generated with Creative Executable\n\nTarget: {} / {}. Source code is generated by a model; inspect it before use.\n\nThis ZIP contains sources and scripts, not installed compilers or provider credentials.\n\n1. Install the project toolchain ({}).\n2. Run build.{} from this directory.\n3. Run run.{} to open the app.\n\n{}\n\nThe CREXE build ran on the local host. A working directory is not security isolation.\n", std::env::consts::OS, std::env::consts::ARCH, if dotnet { ".NET 8 SDK, plus .NET Desktop Runtime for a framework-dependent Windows UI" } else { "see build script for compiler and dependencies" }, if windows { "bat" } else { "sh" }, if windows { "bat" } else { "sh" }, if dotnet { "test runs the generated application's --crexe-self-test checks. publish creates a framework-dependent distribution; it does not bundle the .NET runtime." } else { "No engine-owned self-test or publish operation is defined for this legacy target." });
    fs::write(root.join("CREXE-README.md"), instructions)?;
    sources.insert("CREXE-README.md".into());
    let archive = fs::File::create(root.join(ARCHIVE))?;
    let mut zip = zip::ZipWriter::new(archive);
    for relative in sources {
        if relative == Path::new(ARCHIVE) {
            bail!("Generated sources must not overwrite the source archive");
        }
        let file = root.join(&relative);
        paths::reject_links(&file)?;
        let mode = if relative.extension().is_some_and(|ext| ext == "sh") {
            0o755
        } else {
            0o644
        };
        zip.start_file(
            relative.to_string_lossy().replace('\\', "/"),
            zip::write::SimpleFileOptions::default().unix_permissions(mode),
        )?;
        std::io::copy(&mut fs::File::open(file)?, &mut zip)?;
    }
    zip.finish()?.sync_all()?;
    Ok(())
}

fn quote(arg: &str, windows: bool) -> Result<String> {
    if arg.chars().any(|c| c == '\n' || c == '\r' || c == '\0') {
        bail!("Multiline command argument cannot be exported as a script");
    }
    if windows {
        if arg.contains('"') || arg.contains('%') {
            bail!("Command argument containing quotes or percent cannot be safely exported to BAT; use a project script");
        }
        Ok(format!("\"{arg}\""))
    } else {
        Ok(format!("'{}'", arg.replace('\'', "'\"'\"'")))
    }
}

pub(crate) fn export(revision: &Path, destination: Option<&Path>) -> Result<()> {
    let Some(destination) = destination else {
        return Ok(());
    };
    let destination = std::path::absolute(destination)?;
    paths::reject_links(&destination)?;
    let parent = destination.parent().context("Invalid export path")?;
    fs::create_dir_all(parent)?;
    let mut staged = tempfile::NamedTempFile::new_in(parent)?;
    std::io::copy(
        &mut fs::File::open(revision.join(ARCHIVE))
            .context("No source archive in this revision; rebuild it")?,
        staged.as_file_mut(),
    )?;
    staged.flush()?;
    staged
        .persist_noclobber(&destination)
        .map_err(|error| error.error)
        .context("Export destination already exists or is not writable; select a new filename")?;
    println!("Source ZIP: {}", destination.display());
    Ok(())
}
